project_id = "lfnvnxeymkhyzzsvadbp"

[functions.create-manager]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.hotel-sync]
verify_jwt = false

[functions.hotel-reservations]
verify_jwt = false

[functions.hotel-sync-confirm]
verify_jwt = false

[functions.send-booking-to-hotel]
verify_jwt = false

[functions.send-cancellation-to-hotel]
verify_jwt = false

[functions.get-bookings-by-email]
verify_jwt = false

[functions.scheduled-cleanup]
verify_jwt = false

[functions.get-cancellation-policy]
verify_jwt = false

[functions.guest-cancel-booking]
verify_jwt = false

[functions.hotel-company-api]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.manage-admin-user]
verify_jwt = false
